### ISSUE TITLE
How to run this??

### ISSUE THREAD

**Issue by sudnyeshtalekar** [Saakshaat/Sahayak#1]

**Comment by Saakshaat** [comment]
@sudnyeshtalekar I believe most dependencies used in this project are depreciated since it uses Python 2.7 and I haven't maintained this in a year. So I'm fairly certain that this project won't run in its current state.

To answer your question, you have to clone the repo and run the `main.py` script which would shoot up the assistant. This will listen for audio inputs from you and perform a requested command.

I think it might be a good idea to take care of the depreciation; if you want to fix that, feel free to open a PR!

**Comment by sudnyeshtalekar** [comment]
Great then,will try and fix it and send a PR

**Comment by Saakshaat** [comment]
Great @sudnyeshtalekar, I'll assign you a new issue!

**Comment by sudnyeshtalekar** [comment]
`pip install vext`
`pip install vext.gi`
used this to install the gi module in venv. 
still getting the error module not found
![image](https://user-images.githubusercontent.com/48767586/89446949-d8194600-d772-11ea-8f3c-c0897d5527d5.png)

**Comment by Saakshaat** [comment]
Open another issue for this.
